### ISSUE TITLE
Use own robot arm and gripper

### ISSUE THREAD

**Issue by Tranthanhbao198** [srl-ethz/faive_gym_oss#6]
Hi there,
I am a newbie in isaacgym, I want to use my robot arm and gripper for project “Franka cube stack”, so, can you guys please help me by letting me know step by step which files I need to modify to replace the robot arm Franka and its gripper with my robot arm and my gripper? And in these files, which code lines do I need to modify? 
Thank you so much.

**Comment by Yasu31** [comment]
Hello,
I think you mean the FrankaCubeStack environment in IsaacGym (linking your [other question on that repo](https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/issues/217) here so it can be cross-referenced easily for the future)

They define the Franka arm + gripper as a URDF file, which is saved in https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/blob/main/assets/urdf/franka_description/robots/franka_panda_gripper.urdf . You can look at the ROS URDF tutorials to learn how to create a URDF for your own custom robot (https://docs.ros.org/en/iron/Tutorials/Intermediate/URDF/URDF-Main.html).

Once you do that, you should be able to change this line to refer to your robot instead of `franka_panda_gripper.urdf`, and it will show up in the FrankaCubeStack environment.
https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/blob/main/isaacgymenvs/cfg/task/FrankaCubeStack.yaml#L34

If your robot has a different DoF you might have to update some of the python code (https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/blob/main/isaacgymenvs/tasks/franka_cube_stack.py) to match it as well, and IsaacGym might not support all URDF features so you might have to experiment around a bit.
