### ISSUE TITLE
How to play a trained policy and deploy a trained agent?

### ISSUE THREAD

**Issue by YechenZhou** [srl-ethz/faive_gym_oss#8]
Thank you very much for providing such a great library for us to learn and use. I deployed and trained according to your library and obtained a trained policy, but I want to test the policy in the physX simulation environment of isaac gym and deploy a trained agent. Is there any code I can refer to? Looking forward to your reply. Thank you.

**Comment by Yasu31** [comment]
Thanks for using the library! Yes, you can just pass `test=True` when you run train.py (also set the checkpoint parameter too, please refer to the README for how to use them) and it will just roll out the policy, without training the policy further.

**Comment by YechenZhou** [comment]
Thanks for your reply. If I want to test the trained policy in Pybullet physics engine, how can I do it? Are there any reference examples or suggestions? @Yasu31

**Comment by Yasu31** [comment]
That would be quite a bit more complex, since you would need to

1. re-create the entire simulation environment in PyBullet
2. export the MLP weights of the RL policy to a file (that part is described in the README)
3. implement the same observations and actions in Pybullet, and connect it to the policy MLP which receives observations and executes the actions

also the physics would be a bit different between simulators, so it might not work as well as in IsaacGym. It would almost be like you're trying to do a sim2real transfer, so you should enable domain randomization when training the policy so it can handle this domain shift.

**Comment by YechenZhou** [comment]
Thanks, I'll try.
